version: '3.8'

networks:
  default:
    driver: bridge
    external: false

services:
  eth-boot:
    build:
      context: ./
      dockerfile: boot-node/Dockerfile
    image: sun/boot-node:latest
    container_name: eth-boot
    restart: on-failure

  eth-miner1:
    build:
      context: ./
      dockerfile: mining-node1/Dockerfile
    image: sun/mining-node1:latest
    container_name: eth-miner1
    restart: on-failure
    depends_on: 
      - eth-boot

  eth-miner2:
    build:
      context: ./
      dockerfile: mining-node2/Dockerfile
    image: sun/mining-node2:latest
    container_name: eth-miner2
    restart: on-failure
    depends_on: 
      - eth-boot
      - eth-miner1

  eth-miner3:
    build:
      context: ./
      dockerfile: mining-node3/Dockerfile
    image: sun/mining-node3:latest
    container_name: eth-miner3
    restart: on-failure
    depends_on: 
      - eth-boot
      - eth-miner2

  eth-member1:
    build:
      context: ./
      dockerfile: member-node/Dockerfile
    image: sun/member-node:latest
    container_name: eth-member1
    restart: on-failure
    depends_on: 
      - eth-boot
      - eth-miner3

  eth-member2:
    build:
      context: ./
      dockerfile: member-node/Dockerfile
    image: sun/member-node:latest
    container_name: eth-member2
    restart: on-failure
    depends_on: 
      - eth-boot
      - eth-member1
